# Generated by Django 4.2.23 on 2025-08-04 05:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع الإجازة')),
                ('category', models.CharField(choices=[('annual', 'إجازة سنوية'), ('sick', 'إجازة مرضية'), ('maternity', 'إجازة وضع'), ('paternity', 'إجازة والدية'), ('hajj', 'إجازة حج'), ('emergency', 'إجازة طارئة'), ('study', 'إجازة دراسية'), ('unpaid', 'إجازة بدون راتب'), ('compensatory', 'إجازة تعويضية'), ('other', 'أخرى')], max_length=20, verbose_name='الفئة')),
                ('max_days_per_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الحد الأقصى في السنة')),
                ('max_consecutive_days', models.IntegerField(blank=True, null=True, verbose_name='الحد الأقصى المتتالي')),
                ('is_paid', models.BooleanField(default=True, verbose_name='مدفوعة الراتب')),
                ('carry_forward', models.BooleanField(default=False, verbose_name='قابلة للترحيل')),
                ('max_carry_forward_days', models.IntegerField(blank=True, null=True, verbose_name='الحد الأقصى للترحيل')),
                ('requires_medical_certificate', models.BooleanField(default=False, verbose_name='تتطلب شهادة طبية')),
                ('advance_notice_days', models.IntegerField(default=3, verbose_name='فترة الإشعار المسبق (أيام)')),
                ('gender_specific', models.CharField(choices=[('both', 'كلا الجنسين'), ('male', 'ذكور فقط'), ('female', 'إناث فقط')], default='both', max_length=10, verbose_name='خاص بالجنس')),
                ('minimum_service_months', models.IntegerField(default=0, verbose_name='الحد الأدنى لفترة الخدمة (شهر)')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='companies.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'نوع إجازة',
                'verbose_name_plural': 'أنواع الإجازات',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('days_count', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='عدد الأيام')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الاتصال')),
                ('contact_address', models.TextField(blank=True, verbose_name='عنوان الاتصال')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leaves/attachments/', verbose_name='مرفق')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجعة')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('delegate_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_tasks', to='employees.employee', verbose_name='تفويض المهام إلى')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee', verbose_name='الموظف')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='leaves.leavetype', verbose_name='نوع الإجازة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to='employees.employee', verbose_name='راجع بواسطة')),
            ],
            options={
                'verbose_name': 'طلب إجازة',
                'verbose_name_plural': 'طلبات الإجازات',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('entitled_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='الأيام المستحقة')),
                ('used_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='الأيام المستخدمة')),
                ('carried_forward_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='الأيام المرحلة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee', verbose_name='الموظف')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leaves.leavetype', verbose_name='نوع الإجازة')),
            ],
            options={
                'verbose_name': 'رصيد إجازة',
                'verbose_name_plural': 'أرصدة الإجازات',
                'ordering': ['-year', 'employee'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العطلة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('holiday_type', models.CharField(choices=[('national', 'عطلة وطنية'), ('religious', 'عطلة دينية'), ('company', 'عطلة الشركة')], default='national', max_length=20, verbose_name='نوع العطلة')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='عطلة متكررة سنوياً')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='companies.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'عطلة رسمية',
                'verbose_name_plural': 'العطل الرسمية',
                'ordering': ['date'],
                'unique_together': {('company', 'date')},
            },
        ),
    ]
