# Generated by Django 4.2.23 on 2025-08-04 05:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم الشركة كما هو مسجل رسمياً', max_length=200, verbose_name='اسم الشركة')),
                ('commercial_registration', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='السجل التجاري يجب أن يكون 10 أرقام', regex='^\\d{10}$')], verbose_name='السجل التجاري')),
                ('tax_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='الرقم الضريبي يجب أن يكون 15 رقم', regex='^\\d{15}$')], verbose_name='الرقم الضريبي')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='شعار الشركة')),
                ('address', models.TextField(help_text='العنوان الكامل للشركة', verbose_name='العنوان')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يبدأ بـ +966 ويتبعه 9 أرقام', regex='^\\+966[0-9]{9}$')], verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, null=True, verbose_name='الموقع الإلكتروني')),
                ('settings', models.JSONField(default=dict, help_text='إعدادات مخصصة لكل شركة', verbose_name='إعدادات الشركة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسم')),
                ('description', models.TextField(blank=True, verbose_name='وصف القسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='companies.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('level', models.CharField(choices=[('entry', 'مبتدئ'), ('junior', 'صغير'), ('senior', 'كبير'), ('lead', 'قائد'), ('manager', 'مدير'), ('director', 'مدير عام')], default='entry', max_length=50, verbose_name='المستوى')),
                ('description', models.TextField(blank=True, verbose_name='وصف المنصب')),
                ('requirements', models.TextField(blank=True, verbose_name='المتطلبات')),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأدنى للراتب')),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأعلى للراتب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='companies.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'منصب وظيفي',
                'verbose_name_plural': 'المناصب الوظيفية',
                'ordering': ['title'],
            },
        ),
    ]
