# Generated by Django 4.2.23 on 2025-08-04 05:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_tolerance_minutes', models.IntegerField(default=15, verbose_name='الحد المسموح للتأخير (دقيقة)')),
                ('late_deduction_per_minute', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='خصم لكل دقيقة تأخير')),
                ('absence_deduction_per_day', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='خصم يوم الغياب')),
                ('overtime_rate_weekday', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=3, verbose_name='معدل الإضافي في أيام العمل')),
                ('overtime_rate_weekend', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=3, verbose_name='معدل الإضافي في العطل')),
                ('require_location_tracking', models.BooleanField(default=True, verbose_name='تتبع الموقع مطلوب')),
                ('allowed_distance_meters', models.IntegerField(default=100, verbose_name='المسافة المسموحة بالمتر')),
                ('auto_checkout_hours', models.IntegerField(default=12, verbose_name='انصراف تلقائي بعد (ساعة)')),
            ],
            options={
                'verbose_name': 'سياسة الحضور',
                'verbose_name_plural': 'سياسات الحضور',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('break_start_time', models.TimeField(blank=True, null=True, verbose_name='بداية الاستراحة')),
                ('break_end_time', models.TimeField(blank=True, null=True, verbose_name='نهاية الاستراحة')),
                ('check_in_location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='خط العرض للحضور')),
                ('check_in_location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='خط الطول للحضور')),
                ('check_out_location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='خط العرض للانصراف')),
                ('check_out_location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='خط الطول للانصراف')),
                ('work_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='ساعات العمل')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='الساعات الإضافية')),
                ('late_minutes', models.IntegerField(default=0, verbose_name='دقائق التأخير')),
                ('early_leave_minutes', models.IntegerField(default=0, verbose_name='دقائق المغادرة المبكرة')),
                ('break_minutes', models.IntegerField(default=0, verbose_name='دقائق الاستراحة')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('early_leave', 'مغادرة مبكرة'), ('partial', 'حضور جزئي'), ('holiday', 'عطلة'), ('leave', 'إجازة')], default='present', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_manual_entry', models.BooleanField(default=False, verbose_name='إدخال يدوي')),
                ('manual_entry_reason', models.TextField(blank=True, verbose_name='سبب الإدخال اليدوي')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
                'ordering': ['-date', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], verbose_name='يوم الأسبوع')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية')),
                ('break_start_time', models.TimeField(blank=True, null=True, verbose_name='بداية الاستراحة')),
                ('break_end_time', models.TimeField(blank=True, null=True, verbose_name='نهاية الاستراحة')),
                ('is_working_day', models.BooleanField(default=True, verbose_name='يوم عمل')),
                ('effective_from', models.DateField(verbose_name='ساري من')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='ساري حتى')),
            ],
            options={
                'verbose_name': 'جدولة عمل',
                'verbose_name_plural': 'جدولة العمل',
                'ordering': ['employee', 'weekday'],
            },
        ),
    ]
