# Generated by Django 4.2.23 on 2025-08-04 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('attendance', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='employees.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendance', to='employees.employee', verbose_name='وافق عليه'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee', verbose_name='الموظف'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policy', to='companies.company', verbose_name='الشركة'),
        ),
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together={('employee', 'weekday', 'effective_from')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('employee', 'date')},
        ),
    ]
