# Generated by Django 4.2.23 on 2025-08-04 05:36

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndOfServiceBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_years', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='سنوات الخدمة')),
                ('last_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='آخر راتب')),
                ('calculated_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المحسوب')),
                ('termination_reason', models.CharField(choices=[('resignation', 'استقالة'), ('termination', 'فصل'), ('retirement', 'تقاعد'), ('death', 'وفاة')], max_length=20, verbose_name='سبب انتهاء الخدمة')),
                ('calculation_date', models.DateField(verbose_name='تاريخ الحساب')),
                ('is_paid', models.BooleanField(default=False, verbose_name='مدفوع')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end_of_service_benefit', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'مكافأة نهاية الخدمة',
                'verbose_name_plural': 'مكافآت نهاية الخدمة',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(verbose_name='ساري من')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الأساسي')),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='بدل السكن')),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='بدل المواصلات')),
                ('food_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='بدل الطعام')),
                ('other_allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='بدلات أخرى')),
                ('insurance_percentage', models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=5, verbose_name='نسبة التأمين %')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'راتب موظف',
                'verbose_name_plural': 'رواتب الموظفين',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المكون')),
                ('component_type', models.CharField(choices=[('allowance', 'بدل'), ('deduction', 'خصم'), ('bonus', 'مكافأة'), ('overtime', 'إضافي')], max_length=20, verbose_name='نوع المكون')),
                ('calculation_type', models.CharField(choices=[('fixed', 'مبلغ ثابت'), ('percentage', 'نسبة مئوية'), ('formula', 'معادلة حسابية')], max_length=20, verbose_name='طريقة الحساب')),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='القيمة')),
                ('formula', models.TextField(blank=True, help_text='للاستخدام مع طريقة الحساب بالمعادلة', verbose_name='المعادلة الحسابية')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='خاضع للضريبة')),
                ('affects_overtime', models.BooleanField(default=False, verbose_name='يؤثر على حساب الإضافي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='companies.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'مكون راتب',
                'verbose_name_plural': 'مكونات الراتب',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='الشهر')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الأساسي')),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='بدل السكن')),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='بدل المواصلات')),
                ('food_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='بدل الطعام')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='مبلغ الإضافي')),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='المكافآت')),
                ('other_allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='بدلات أخرى')),
                ('insurance_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='خصم التأمين')),
                ('absence_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='خصم الغياب')),
                ('late_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='خصم التأخير')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='خصومات أخرى')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الإجمالي')),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي الخصومات')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='صافي الراتب')),
                ('working_days', models.IntegerField(default=0, verbose_name='أيام العمل')),
                ('present_days', models.IntegerField(default=0, verbose_name='أيام الحضور')),
                ('absent_days', models.IntegerField(default=0, verbose_name='أيام الغياب')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='ساعات الإضافي')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('calculated', 'محسوب'), ('approved', 'معتمد'), ('paid', 'مدفوع')], default='draft', max_length=20, verbose_name='الحالة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to='employees.employee', verbose_name='اعتمد بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'كشف راتب',
                'verbose_name_plural': 'كشوف الرواتب',
                'ordering': ['-year', '-month', 'employee'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
