# Generated by Django 4.2.23 on 2025-08-04 05:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='رقم تعريفي فريد للموظف', max_length=20, unique=True, verbose_name='رقم الموظف')),
                ('national_id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يكون 10 أرقام', regex='^\\d{10}$')], verbose_name='رقم الهوية الوطنية')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='اسم العائلة')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يبدأ بـ +966 ويتبعه 9 أرقام', regex='^\\+966[0-9]{9}$')], verbose_name='رقم الهاتف')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('nationality', models.CharField(default='سعودي', max_length=50, verbose_name='الجنسية')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employees/profiles/', verbose_name='الصورة الشخصية')),
                ('hire_date', models.DateField(verbose_name='تاريخ التوظيف')),
                ('contract_type', models.CharField(choices=[('permanent', 'دائم'), ('temporary', 'مؤقت'), ('contract', 'تعاقد'), ('part_time', 'دوام جزئي')], default='permanent', max_length=20, verbose_name='نوع العقد')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الأساسي')),
                ('work_hours_per_day', models.IntegerField(default=8, verbose_name='ساعات العمل اليومية')),
                ('work_days_per_week', models.IntegerField(default=6, verbose_name='أيام العمل الأسبوعية')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('suspended', 'موقوف'), ('terminated', 'منتهي الخدمة'), ('on_leave', 'في إجازة')], default='active', max_length=20, verbose_name='حالة الموظف')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الخدمة')),
                ('termination_reason', models.TextField(blank=True, verbose_name='سبب انتهاء الخدمة')),
                ('emergency_contact_name', models.CharField(max_length=100, verbose_name='اسم جهة الاتصال للطوارئ')),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name='رقم هاتف الطوارئ')),
                ('emergency_contact_relation', models.CharField(max_length=50, verbose_name='صلة القرابة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.company', verbose_name='الشركة')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='companies.department', verbose_name='القسم')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee', verbose_name='المدير المباشر')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='companies.position', verbose_name='المنصب')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_copy', 'صورة الهوية'), ('passport', 'جواز السفر'), ('contract', 'العقد'), ('certificate', 'الشهادة'), ('medical_report', 'التقرير الطبي'), ('bank_account', 'كشف حساب بنكي'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الوثيقة')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الوثيقة')),
                ('file', models.FileField(upload_to='employees/documents/', verbose_name='الملف')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee', verbose_name='الموظف')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'وثيقة موظف',
                'verbose_name_plural': 'وثائق الموظفين',
                'ordering': ['-upload_date'],
            },
        ),
    ]
